### ISSUE TITLE
Feature (un)request: Remove .rxWithWd for withr::with_dir()

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/lotri#4]
To simplify the code base, I think it would be good to remove `.rxWithWd()` in favor of `withr::with_dir()` or `withr::with_tempdir()`.  It's used a couple of times in the main rxode2.R code, so it's not just a test change (so, I thought I'd ask first).

**Comment by mattfidler** [comment]
Mostly an issue of dependencies.  Perhaps you mentioned it in `lotri()` because you could export it in lotri and not add it as a depedency in `rxode2`.  That would work for me, though it may be a bit strange to use `lotri::with_dir` and `lotri::with_tempdir`.  In that case you could put it as a suggest in `rxode2` and simply use the function directly.

**Comment by billdenney** [comment]
Hmm.  Lemme think about the re-export from `lotri` option.  My initial thought is that I'd prefer not to do that (since we're really just using `withr`).  But, if there are issues with dependency count on CRAN, maybe that is the way to go.

For things where we're rewriting them in both rxode2 and nlmixr2, I do think that we should move it to just be in rxode2 since that dependency already exists.

More thinking is needed.

**Comment by mattfidler** [comment]
We are really close to the 20 imports limit in `rxode2`.  (18 currently).

**Comment by mattfidler** [comment]
`lotri()` has 4

**Comment by mattfidler** [comment]
I havr those issues too...
